set_property PACKAGE_PIN V17 [get_ports {a[0]}]
set_property PACKAGE_PIN V16 [get_ports {a[1]}]
set_property PACKAGE_PIN U16 [get_ports {y[0]}]
set_property PACKAGE_PIN E19 [get_ports {y[1]}]
set_property PACKAGE_PIN U19 [get_ports {y[2]}]
set_property PACKAGE_PIN V19 [get_ports {y[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {a y}]
